config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { 
      :sessions => "admins/sessions", 
      :registrations => "admins/registrations", 
      :passwords => "admins/passwords", 
      :confirmations => "admins/confirmations"
    }

  devise_for :users, :controllers => { 
      :sessions => "users/sessions", 
      :registrations => "users/registrations", 
      :passwords => "users/passwords", 
      :confirmations => "users/confirmations"
    }
    

  devise_scope :user do
    authenticated :user do
      root 'users#home', as: :user_home
    end

    unauthenticated do
      root 'users#dashboard', as: :unauthenticated_root
    end

    get 'users/sign_in', to: 'users/sessions#new' , :path => "user/login"
    delete 'users/sign_out', to: 'users/sessions#destroy' , :path => "user/logout" 
  end
  
  

  devise_scope :admin do
    authenticated :admin do
      root 'admins/dashboard#home'
    end

    unauthenticated do
      root 'admins/sessions#new', as: :unauthenticated_admin_root
    end

    get 'admins/sign_in', to: 'admins/sessions#new' , :path => "admin"
    get 'admins/sign_up', to: 'admins/registrations#new' , :path => "admin/sign_up"
    delete 'admins/sign_out', to: 'admins/sessions#destroy' , :path => "admin/logout"
  end

  namespace :admins do
    resources :users
    resources :static_pages
    resources :inquiries
    get 'home' => 'dashboard#home'
    get 'home/:id' => 'users#show'
   end

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resource :admin, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  get 'users/:id' => 'users#show'

  get '/home' => 'users#home'

  get '/dashboard' => 'users#dashboard'

  get 'contact-us' => 'inquiries#new',as: 'contact_us'

  get '/:route' => 'users#page'

  resources :inquiries , :only=>[:new,:create]

  match '*unmatched_route', :to => 'application#raise_not_found' ,:via => [:all]

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base

  validates :name, :presence => true
  validates :page_route, :presence => true
  validates :label, :presence => true
  validates_uniqueness_of :label

  scope :filter,lambda { |column , value| where("#{column} like ?", "%#{value}%") }
end

app/controllers/admins/static_pages_controller.rb
class Admins::StaticPagesController < ApplicationController
  
  layout 'admin'

  before_action :authenticate_admin!

  helper_method :sort_column, :sort_direction

	def new
		@static_page = StaticPage.new
	end

	def create
		@static_page = StaticPage.create(static_page_params)
    if @static_page.save
      redirect_to admins_static_pages_path, notice: I18n.t("general.create_a_page")
    else
      render action: "new"
    end
	end
		
	def index
    @static_pages = StaticPage.filter(:name,params[:name]).filter(:label,params[:label]).filter(:page_route,params[:page_route]).order("#{sort_column} #{sort_direction}").paginate(page: params[:page], per_page: 5)
  end

  def show
  	@static_page = StaticPage.find_by_id(params[:id])
  end

  def page
    @static_page = StaticPage.find_by(page_route: params[:route])
  end

  def edit
  	@static_page = StaticPage.find_by_id(params[:id])
  end

  def update
  	@static_page = StaticPage.find_by_id(params[:id])
  	if @static_page.update_attributes(static_page_params)
  		flash[:success] = I18n.t("general.update_a_page")
  		redirect_to admins_static_pages_path
  	else
  		render "back"
  	end
  end

  def destroy
    @static_page = StaticPage.find(params[:id])
    @static_page.destroy
    redirect_to admins_static_pages_path, notice: I18n.t("general.destroy_a_page")
  end  


  private
  
  def static_page_params
  	params.require(:static_page).permit(:name, :content, :page_route, :label)
  end

  def sort_column
    StaticPage.column_names.include?(params[:column]) ? params[:column] : (params[:column] ? params[:column] : "name")
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/static_pages/_errors.html.haml
- if @static_page.errors.any?
  #error_explanation
    %h2
      = pluralize(@static_page.errors.count, "error")
      prevented this record from being saved:
    %ul
      - @static_page.errors.full_messages.each do |msg|
        %li= msg

app/views/admins/static_pages/_filters.html.haml
.panel
  = form_tag admins_static_pages_path, :method=> "get", :remote => true , :id => "static_page_search" do
    = text_field_tag :name,nil,:class => "form-control filter_txt_field",placeholder: 'Name'
    = text_field_tag :label,nil,:class => "form-control filter_txt_field",placeholder: 'Label'
    = text_field_tag :page_route,nil,:class => "form-control filter_txt_field",placeholder: 'Page Route'
    = button_tag(type: "submit", class: "btn btn-info filter_btn") do
      Filter
      %i.glyphicon.glyphicon-search   
    = link_to "Clear Filter", request.path, class:"btn btn-info filter_btn"

app/views/admins/static_pages/_form.html.haml
.row
	.col-xs-12
		.col-lg-12
			.row
				.col-lg-12
					= form_for [:admins, static_page] do |f|
						= render 'errors'
						%br/
						%label Name :
						%br/
						= f.text_field :name, class: "form-control"
						%br/
						%label Content :
						= f.cktext_area :content ,:input_html => { :class => "ckeditor" } ,:label => false
						%br/
						%label Page Route :
						= f.text_field :page_route, class: "form-control"
						%br/
						%label Label :
						= f.text_field :label, class: "form-control"
						%br
						= f.submit 'Submit', :class => 'btn btn-success'

app/views/admins/static_pages/_staticpages.html.haml
%table.table.table-hover
  %thead
    %tr
      %th=sortable "id"    
      %th=sortable "name"
      %th=sortable "label"
      %th=sortable "page_route"
      %th Content
      %th Actions
  %tbody
    - @static_pages.each do |static_page|
      %tr
      %td
        = link_to static_page.id, admins_static_page_path(static_page.id)
      %td
        = static_page.name
      %td
        = static_page.label
      %td
        = static_page.page_route
      %td
        %textarea{:cols => "25", :rows => "2"}
          = static_page.content
      %td
        = link_to admins_static_page_path(id: static_page.id) do
          %span.glyphicon.glyphicon-eye-open
        |
        = link_to edit_admins_static_page_path(id: static_page.id) do
          %span.glyphicon.glyphicon-pencil
        |
        = link_to admins_static_page_path(static_page.id), method: :delete, data: {confirm: "Are you Sure ?"}  do
          %span.glyphicon.glyphicon-trash
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :column, params[:column]
= will_paginate @static_pages            

app/views/admins/static_pages/edit.html.haml
= render partial: 'admins/dashboard/sidebar'
.row
  .col-lg-8.main
    .row
      %ol.breadcrumb
        %li
          %a{:href => "/admins/home"}
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
        %li.active= @static_page.class
    .row
      .col-lg-12
        .panel.panel-default
          %h2.panel-heading
            Edit Static Page
          .panel-body
            = render partial: 'admins/static_pages/form', locals: {static_page: @static_page}

app/views/admins/static_pages/index.html.haml
= render partial: 'admins/dashboard/sidebar'
.row
  .col-lg-9.main
    .row
      %ol.breadcrumb
        %li
          %a{:href => "/admins/home"}
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
        %li.active
          = I18n.t("admin.static_pages")
    .row
      .panel.panel-default
        .panel-heading
          .col-lg-6
            %h3
              = I18n.t("admin.static_pages")
          .col-lg-3
            .col-lg-2
            .col-lg-1.adduserbtn
              = link_to new_admins_static_page_path, class: "btn btn-info" do
                %i.glyphicon.glyphicon-plus
                %strong
                  = I18n.t("admin.add_static_pages")
          .col-lg-3
            .col-lg-2
            .col-lg-1.filterbtn
              = I18n.t("admin.filters")
        .panel-body
          #staticpages.col-md-9
            = render 'staticpages'            
          #forms.col-md-3
            = render 'filters'

app/views/admins/static_pages/index.js.erb
$("#staticpages").html("<%= escape_javascript(render("staticpages")) %>");

app/views/admins/static_pages/new.html.haml
= render partial: 'admins/dashboard/sidebar'
.row
  .col-lg-8.main
    .row
      %ol.breadcrumb
        %li
          %a{:href => "/admins/home"}
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
        %li.active= @static_page.class
    .row
      .col-lg-12
        .panel-info
          .panel-heading
            New Static Page
          .panel-body
            = render partial: 'admins/static_pages/form', locals: {static_page: @static_page}

app/views/admins/static_pages/page.html.haml
.row
  .col-xs-12.col-lg-10.col-lg-offset-2.text-left
    - if @static_page
      %h1.pageTitle
        = @static_page.name.html_safe
      %p
        - if @static_page.present? and @static_page.content.present?
          = @static_page.content.html_safe
    - else
      %h1.pageTitle
        = I18n.t("page_not_found.text_p")

app/views/admins/static_pages/show.html.haml
= render partial: 'admins/dashboard/sidebar'
.col-lg-8.main
  .row
    %ol.breadcrumb
      %li
        %a{:href => "/admins/home"}
          %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
      %li.active= @static_page.class
  .row
    .panel.panel-default
      .panel-heading
        .col-lg-6
          %h3
            = I18n.t("admin.static_pages")
        .col-lg-2
          .col-lg-2
          .col-lg-1
        .col-lg-4.adduserbtn
          = link_to edit_admins_static_page_path(@static_page.id), class: "btn btn-primary" do
            %i.glyphicon.glyphicon-pencil
            %strong Edit
          = link_to admins_static_pages_path, class: "btn btn-info" do
            %i.glyphicon.glyphicon-arrow-left
            %strong Back
      .panel-body
        %ul.nav.nav-tabs
          %li.active
            %a{"data-toggle" => "tab", :href => "#tab1default"} Basic Info
          %li
            %a{"data-toggle" => "tab", :href => "#tab2default"} View Content
        .tab-content
          #tab1default.tab-pane.fade.in.active
            .col-lg-6
              .panel-body
                .col-lg-6
                  .col-lg-7
                    %label Name :
                  .col-lg-5
                    = @static_page.name
                  .col-lg-7
                    %label Label:
                  .col-lg-5
                    = @static_page.label
                  %br/
          #tab2default.tab-pane.fade
            .col-lg-6
              .panel-body
                .col-lg-12
                  = @static_page.content