config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { 
      :sessions => "admins/sessions", 
      :registrations => "admins/registrations", 
      :passwords => "admins/passwords", 
      :confirmations => "admins/confirmations"
    }

  devise_for :users, :controllers => { 
      :sessions => "users/sessions", 
      :registrations => "users/registrations", 
      :passwords => "users/passwords", 
      :confirmations => "users/confirmations"
    }
    

  devise_scope :user do
    authenticated :user do
      root 'users#home', as: :user_home
    end

    unauthenticated do
      root 'users#dashboard', as: :unauthenticated_root
    end

    get 'users/sign_in', to: 'users/sessions#new' , :path => "user/login"
    delete 'users/sign_out', to: 'users/sessions#destroy' , :path => "user/logout" 
  end
  
  

  devise_scope :admin do
    authenticated :admin do
      root 'admins/dashboard#home'
    end

    unauthenticated do
      root 'admins/sessions#new', as: :unauthenticated_admin_root
    end

    get 'admins/sign_in', to: 'admins/sessions#new' , :path => "admin"
    get 'admins/sign_up', to: 'admins/registrations#new' , :path => "admin/sign_up"
    delete 'admins/sign_out', to: 'admins/sessions#destroy' , :path => "admin/logout"
  end

  namespace :admins do
    resources :users
    resources :static_pages
    resources :inquiries
    get 'home' => 'dashboard#home'
    get 'home/:id' => 'users#show'
   end

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resource :admin, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  get 'users/:id' => 'users#show'

  get '/home' => 'users#home'

  get '/dashboard' => 'users#dashboard'

  get 'contact-us' => 'inquiries#new',as: 'contact_us'

  get '/:route' => 'users#page'

  resources :inquiries , :only=>[:new,:create]

  match '*unmatched_route', :to => 'application#raise_not_found' ,:via => [:all]

end

app/models/user.rb
class User < ActiveRecord::Base
	rolify

  extend FriendlyId
  friendly_id :full_name, use: [:slugged,:finders]  
	
  after_create :assign_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum user_role: [:admin, :user, :superadmin, :customer]

  scope :filter, lambda { |column , value| where("#{column} like ?", "%#{value}%") }
  
  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def should_generate_new_friendly_id?
    new_record? || self.slug.nil? || self.slug.blank? || (self.first_name.present? && self.last_name.present?)# you can add more condition here
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

	layout 'admin'

	before_action :authenticate_admin!

	helper_method :sort_column, :sort_direction

  def index
		if request.xhr? == 0 and !params.has_key?('direction')
			@users = User.filter(:first_name,params[:first_name]).filter(:last_name,params[:last_name]).filter(:city,params[:city]).order("#{sort_column} #{sort_direction}").paginate(page: params[:page], per_page: 5)
		elsif request.xhr? ==0  and params.has_key?('direction')
			@users = User.all.order("#{sort_column} #{sort_direction}").paginate(page: params[:page], per_page: 5)
		else
			@users = User.all.order("#{sort_column} #{sort_direction}").paginate(page: params[:page], per_page: 5)
		end
  end

  def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.add_role params[:role]
		if @user.save
			redirect_to admins_users_path, notice: I18n.t("general.create_a_user")
		else
			render action: "new"
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.add_role params[:role]
		if @user.update_attributes(edit_user_params)
			redirect_to admins_users_path, notice: I18n.t("general.update_a_user")
		else
			render action: "edit"
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to admins_users_path, notice: I18n.t("general.destroy_a_user")
	end

	private

	def user_params
		params[:user].permit(:first_name, :last_name, :city, :email, :mobile_number, :password, :password_confirmation)
	end

	def edit_user_params
		params[:user].permit(:first_name, :last_name, :city, :email, :mobile_number)
	end

	def sort_column
    User.column_names.include?(params[:column]) ? params[:column] : (params[:column] ? params[:column] : "first_name")
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :configure_sign_up_params, only: [:create]
 before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :city, :mobile_number])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource :except=> [:dashboard,:page]
  before_filter :authenticate_user!,except: [:dashboard,:page]

  def dashboard
  end
 
  def home
  end

  def show
  	@user = User.friendly.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update_password
    @user = User.find(current_user.id)
    if @user.update_with_password(user_params)
      flash[:success] = I18n.t('general.password_updated_successfully')
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      redirect_to root_path
    else
      render "edit"
    end
  end
  
  def page
    @static_page = StaticPage.find_by(page_route: params[:route])
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :current_password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/_edit_form.html.haml
= form_for [:admins, @user] do |f|
  = render 'shared/error_messages'
  %br/
  %label First Name :
  %br/
  = f.text_field :first_name, class: "form-control"
  %br/
  %label Last Name :
  %br/         
  = f.text_field :last_name, class: "form-control"
  %br/
  %label City :
  %br/
  = f.text_field :city, class: "form-control"
  %br/
  %label Mobile No :
  %br/
  = f.text_field :mobile_number, class: "form-control"
  %br/
  %label Add Role:
  = select_tag :role, options_for_select(User.user_roles.map{ |c| [c[0]]}),:class=>'form-control',:prompt=>'Select Role.....'
  %br/  
  = f.submit "Update", class: "btn btn-success"    

app/views/admins/users/_filters.html.haml
.panel
  = form_tag admins_users_path, :method=> "get", :remote => true,         :id => "user_page_search" do
    = text_field_tag :first_name,nil,:class => "form-control filter_txt_field",placeholder: 'First Name'
    = text_field_tag :last_name,nil,:class => "form-control filter_txt_field",placeholder: 'Last Name'
    = text_field_tag :city,nil,:class => "form-control filter_txt_field",placeholder: 'City'
    = button_tag(type: "submit", class: "btn btn-info filter_btn") do
      Filter
      %i.glyphicon.glyphicon-search   
    = link_to "Clear Filter", request.path, class:"btn btn-info filter_btn"

app/views/admins/users/_new_form.html.haml
= form_for [:admins, @user] do |f|
  = render 'shared/error_messages'
  %br/
  %label Email :
  = f.email_field :email, class: "form-control", autofocus: true
  %br/
  %label First Name :
  %br/
  = f.text_field :first_name, class: "form-control"
  %br/
  %label Last Name :
  %br/        
  = f.text_field :last_name, class: "form-control"
  %br/
  %label Password :
  = f.password_field :password, class: "form-control"
  %br/
  %label Password confirmation :
  = f.password_field :password_confirmation, class: "form-control"
  %br/   
  %label City :
  %br/
  = f.text_field :city, class: "form-control"
  %br/
  %label Mobile No :
  %br/
  = f.text_field :mobile_number, class: "form-control"
  %br/
  %label Add Role:
  = select_tag :role, options_for_select(User.user_roles.map{ |c| [c[0]]}),:class=>'form-control',:prompt=>'Select Role.....'
  %br/ 
  = f.submit "Create", class: "btn btn-success"

app/views/admins/users/_users.html.haml
%table.table.table-hover
  %thead
    %tr
      %th=sortable "id"
      %th=sortable "email"
      %th=sortable "first_name"
      %th=sortable "last_name"
      %th=sortable "city"
      %th Mobile No
      %th Actions
  %tbody
    - @users.each do |user|
      %tr
        %td
          = link_to user.id, admins_user_path(user.id)
        %td
          = user.email
        %td
          = user.first_name
        %td
          = user.last_name
        %td
          = user.city
        %td
          = user.mobile_number
        %td
          = link_to admins_user_path(user.id) do
            %span.glyphicon.glyphicon-eye-open
          |
          = link_to edit_admins_user_path(user.id) do
            %span.glyphicon.glyphicon-pencil
          |
          = link_to admins_user_path(user.id), method: :delete, data: {confirm: "Are you Sure ?"}  do
            %span.glyphicon.glyphicon-trash 
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :column, params[:column]
= will_paginate @users

app/views/admins/users/edit.html.haml
= render partial: 'admins/dashboard/sidebar'
.row
  .col-lg-8.main
    .row
      %ol.breadcrumb
        %li
          %a{:href => "/admins/home"}
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
        %li.active= @user.class
    .row
      .col-lg-12
        .panel.panel-default
          %h2.panel-heading
            Edit User Details
          .panel-body
            = render 'edit_form'

app/views/admins/users/index.html.haml
#sidebar
  = render partial: 'admins/dashboard/sidebar'
.row
  .col-lg-9.main
    .row
      %ol.breadcrumb
        %li
          %a{:href => "/admins/home"}
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
        %li.active= @users.table_name.capitalize
    .row
      .panel.panel-default
        .panel-heading
          .col-lg-6
            %h3
              = @users.table_name.capitalize
          .col-lg-3
            .col-lg-2
            .col-lg-1.adduserbtn
              = link_to new_admins_user_path, class: "btn btn-info" do
                %i.glyphicon.glyphicon-plus
                %strong
                  = I18n.t("admin.add_user")
          .col-lg-3
            .col-lg-2
            .col-lg-1.filterbtn
              = I18n.t("admin.filters")
        .panel-body
          #users.col-md-9
            = render 'users'
          #forms.col-md-3
            = render 'filters'

app/views/admins/users/index.js.erb
$("#users").html("<%= escape_javascript(render("users")) %>");
$("#forms").replace("<%= escape_javascript(render("filters")) %>");
$('.pagination > a').attr('data-remote', 'true');

app/views/admins/users/new.html.haml
= render partial: 'admins/dashboard/sidebar'
.row
  .col-lg-8.main
    .row
      %ol.breadcrumb
        %li
          %a{:href => "/admins/home"}
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
        %li.active= @user.class
    .row
      .col-lg-12
        .panel-info
          .panel-heading
            New User
          .panel-body
            = render 'new_form'

app/views/admins/users/show.html.haml
= render partial: 'admins/dashboard/sidebar'
.col-lg-8.main
  .row
    %ol.breadcrumb
      %li
        %a{:href => "/admins/home"}
          %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
      %li.active= @user.class
  .row
    .panel.panel-default
      .panel-heading
        .col-lg-6
          %h3
            = I18n.t("admin.users")
        .col-lg-2
          .col-lg-2
          .col-lg-1
        .col-lg-4.adduserbtn
          = link_to edit_admins_user_path(@user.id), class: "btn btn-primary" do
            %i.glyphicon.glyphicon-pencil
            %strong Edit
          = link_to admins_users_path, class: "btn btn-info" do
            %i.glyphicon.glyphicon-arrow-left
            %strong Back        
      .panel-body
        %ul.nav.nav-tabs
          %li.active
            %a{"data-toggle" => "tab", :href => "#tab1default"} Basic Info
          %li
            %a{"data-toggle" => "tab", :href => "#tab2default"} Roles
        .tab-content
          #tab1default.tab-pane.fade.in.active
            .col-lg-6
              .panel-body
                .col-lg-7
                  %label ID :
                .col-lg-5
                  = @user.id
                .col-lg-7
                  %label Email :
                .col-lg-5
                  = @user.email
                .col-lg-7
                  %label First Name :
                .col-lg-5
                  = @user.first_name
                .col-sm-7
                  %label Last Name :
                .col-sm-5
                  = @user.last_name
                .col-sm-7
                  %label City :
                .col-sm-5
                  = @user.city
                .col-sm-7
                  %label Mobile No :
                .col-sm-5
                  = @user.mobile_number
                %br/
          #tab2default.tab-pane.fade
            %h3
              = @user.roles.map{|r| r.name}.join(",")
            %hr