config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { 
      :sessions => "admins/sessions", 
      :registrations => "admins/registrations", 
      :passwords => "admins/passwords", 
      :confirmations => "admins/confirmations"
    }

  devise_for :users, :controllers => { 
      :sessions => "users/sessions", 
      :registrations => "users/registrations", 
      :passwords => "users/passwords", 
      :confirmations => "users/confirmations"
    }
    

  devise_scope :user do
    authenticated :user do
      root 'users#home', as: :user_home
    end

    unauthenticated do
      root 'users#dashboard', as: :unauthenticated_root
    end

    get 'users/sign_in', to: 'users/sessions#new' , :path => "user/login"
    delete 'users/sign_out', to: 'users/sessions#destroy' , :path => "user/logout" 
  end
  
  

  devise_scope :admin do
    authenticated :admin do
      root 'admins/dashboard#home'
    end

    unauthenticated do
      root 'admins/sessions#new', as: :unauthenticated_admin_root
    end

    get 'admins/sign_in', to: 'admins/sessions#new' , :path => "admin"
    get 'admins/sign_up', to: 'admins/registrations#new' , :path => "admin/sign_up"
    delete 'admins/sign_out', to: 'admins/sessions#destroy' , :path => "admin/logout"
  end

  namespace :admins do
    resources :users
    resources :static_pages
    resources :inquiries
    get 'home' => 'dashboard#home'
    get 'home/:id' => 'users#show'
   end

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resource :admin, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  get 'users/:id' => 'users#show'

  get '/home' => 'users#home'

  get '/dashboard' => 'users#dashboard'

  get 'contact-us' => 'inquiries#new',as: 'contact_us'

  get '/:route' => 'users#page'

  resources :inquiries , :only=>[:new,:create]

  match '*unmatched_route', :to => 'application#raise_not_found' ,:via => [:all]

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :phone,:length=>{:maximum => 10, :allow_nil => true}

  scope :filter,lambda { |column , value| where("#{column} like ?", "%#{value}%") } 
end

app/controllers/admins/inquiries_controller.rb
class Admins::InquiriesController < ApplicationController

  layout 'admin'

  before_action :authenticate_admin!

  helper_method :sort_column, :sort_direction

  def index
    @inquiries = Inquiry.filter(:name,params[:name]).filter(:email,params[:email]).filter(:skype_id,params[:skype_id]).order("#{sort_column} #{sort_direction}").paginate(page: params[:page], per_page: 5)
  end

  def show
    @inquiry = Inquiry.find(params[:id])
  end

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      redirect_to admins_inquiries_path, notice: I18n.t("general.create_a_inquiry")
    else
      render action: "new"
    end
  end

  def edit
    @inquiry = Inquiry.find(params[:id])
  end

  def update
    @inquiry = Inquiry.find(params[:id])
    if @inquiry.update_attributes(inquiry_params)
      redirect_to admins_inquiries_path, notice: I18n.t("general.update_a_inquiry")
    else
      render action: "edit"
    end
  end

  def destroy
    @inquiry = Inquiry.find(params[:id])
    @inquiry.destroy
    redirect_to admins_inquiries_path, notice: I18n.t("general.destroy_a_inquiry")
  end

  private

  def inquiry_params
    params[:inquiry].permit(:name,:email, :phone, :message, :skype_id)
  end

  def sort_column
    Inquiry.column_names.include?(params[:column]) ? params[:column] : (params[:column] ? params[:column] : "name")
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    
    if @inquiry.save
      redirect_to root_path, notice: I18n.t("contact.success_alert")
    else
      render action: "new"
    end
  end

  private

  def inquiry_params
    params[:inquiry].permit(:name, :email, :phone, :message, :skype_id)
  end

  def abc
    puts "h       i"
  end

end

app/views/admins/inquiries/_errors.html.haml
- if @inquiry.errors.any?
  #error_explanation
    %h2
      = pluralize(@inquiry.errors.count, "error")
      prevented this record from being saved:
    %ul
      - @inquiry.errors.full_messages.each do |msg|
        %li= msg

app/views/admins/inquiries/_filters.html.haml
.panel
  = form_tag admins_inquiries_path, :method=> "get", :remote => true ,    :id => "inquiry_page_search" do
    = text_field_tag :name,nil,:class => "form-control filter_txt_field",placeholder: 'Name'
    = text_field_tag :email,nil,:class => "form-control filter_txt_field",placeholder: 'Email'
    = text_field_tag :skype_id,nil,:class => "form-control filter_txt_field",placeholder: 'Skype Id'
    = button_tag(type: "submit", class: "btn btn-info filter_btn") do
      Filter
      %i.glyphicon.glyphicon-search   
    = link_to "Clear Filter", request.path, class:"btn btn-info filter_btn"

app/views/admins/inquiries/_form.html.haml
= form_for [:admins, @inquiry] do |f|
  = render 'errors'
  %br/
  %label Name :
  %br/
  = f.text_field :name, class: "form-control"
  %br/
  %label Email :
  %br/         
  = f.text_field :email, class: "form-control"
  %br/
  %label Phone :
  %br/
  = f.text_field :phone, class: "form-control"
  %br/
  %label Skype Id :
  %br/
  = f.text_field :skype_id, class: "form-control"
  %br/
  %label Message:
  = f.text_area :message, class: "form-control"
  %br/  
  = f.submit "submit", class: "btn btn-success"   

app/views/admins/inquiries/_inquiries.html.haml
%table.table.table-hover
  %thead
    %tr
      %th=sortable "id"
      %th=sortable "name"
      %th=sortable "email"
      %th Phone
      %th=sortable "skype_id"
      %th Actions
  %tbody
    - @inquiries.each do |inquiry|
      %tr
      %td
        = link_to inquiry.id,admins_inquiry_path(inquiry.id)
      %td
        = inquiry.name
      %td
        = inquiry.email
      %td
        = inquiry.phone
      %td
        = inquiry.skype_id
      %td
        = link_to admins_inquiry_path(inquiry.id) do
          %span.glyphicon.glyphicon-eye-open
        |
        = link_to edit_admins_inquiry_path(inquiry.id) do
          %span.glyphicon.glyphicon-pencil
        |
        = link_to admins_inquiry_path(inquiry.id), method: :delete, data: {confirm: "Are you Sure ?"}  do
          %span.glyphicon.glyphicon-trash
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :column, params[:column]
= will_paginate @inquiries            

app/views/admins/inquiries/edit.html.haml
= render partial: 'admins/dashboard/sidebar'
.row
  .col-lg-8.main
    .row
      %ol.breadcrumb
        %li
          %a{:href => "/admins/home"}
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
        %li.active= @inquiry.class
    .row
      .col-lg-12
        .panel.panel-default
          %h2.panel-heading
            Edit Inquiry Details
          .panel-body
            = render 'admins/inquiries/form'

app/views/admins/inquiries/index.html.haml
#sidebar
  = render partial: 'admins/dashboard/sidebar'
.row
  .col-lg-9.main
    .row
      %ol.breadcrumb
        %li
          %a{:href => "/admins/home"}
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
        %li.active= @inquiries.table_name.capitalize
    .row
      .panel.panel-default
        .panel-heading
          .col-lg-6
            %h3
              = @inquiries.table_name.capitalize
          .col-lg-3
            .col-lg-2
            .col-lg-1.adduserbtn
              = link_to new_admins_inquiry_path, class: "btn btn-info" do
                %i.glyphicon.glyphicon-plus
                %strong
                  = I18n.t("admin.add_inquiry")
          .col-lg-3
            .col-lg-2
            .col-lg-1.filterbtn
              = I18n.t("admin.filters")
        .panel-body
          #inquiries.col-md-9
            = render 'inquiries'
          #forms.col-md-3
            = render 'filters'

app/views/admins/inquiries/index.js.erb
$("#inquiries").html("<%= escape_javascript(render("inquiries")) %>");
$("#forms").replace("<%= escape_javascript(render("filters")) %>");
$('.pagination > a').attr('data-remote', 'true');

app/views/admins/inquiries/new.html.haml
= render partial: 'admins/dashboard/sidebar'
.row
  .col-lg-8.main
    .row
      %ol.breadcrumb
        %li
          %a{:href => "/admins/home"}
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
        %li.active= @inquiry.class
    .row
      .col-lg-12
        .panel-info
          .panel-heading
            New Inquiry
          .panel-body
            = render 'admins/inquiries/form'

app/views/admins/inquiries/show.html.haml
= render partial: 'admins/dashboard/sidebar'
.col-lg-8.main
  .row
    %ol.breadcrumb
      %li
        %a{:href => "/admins/home"}
          %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
      %li.active= @inquiry.class
  .row
    .panel.panel-default
      .panel-heading
        .col-lg-6
          %h3
            = I18n.t("admin.inquiries")
        .col-lg-2
          .col-lg-2
          .col-lg-1
        .col-lg-4.adduserbtn
          = link_to edit_admins_inquiry_path(@inquiry.id), class: "btn btn-primary" do
            %i.glyphicon.glyphicon-pencil
            %strong Edit
          = link_to admins_inquiries_path, class: "btn btn-info" do
            %i.glyphicon.glyphicon-arrow-left
            %strong Back        
      .panel-body
        %ul.nav.nav-tabs
          %li.active
            %a{"data-toggle" => "tab", :href => "#tab1default"} Basic Info
          %li
            %a{"data-toggle" => "tab", :href => "#tab2default"} Message
        .tab-content
          #tab1default.tab-pane.fade.in.active
            .col-lg-6
              .panel-body
                .col-lg-7
                  %label Name :
                .col-lg-5
                  = @inquiry.name
                .col-lg-7
                  %label Email :
                .col-lg-5
                  = @inquiry.email
                .col-lg-7
                  %label Phone :
                .col-lg-5
                  = @inquiry.phone
                .col-sm-7
                  %label Skype Id :
                .col-sm-5
                  = @inquiry.skype_id
          #tab2default.tab-pane.fade
            .col-lg-12
              .panel-body
                .col-lg-6
                  = @inquiry.message